In [2]:
import numpy as np
import array

In [3]:
type(np.array([1,2,3,4,56]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,56]) #list

array([ 1,  2,  3,  4, 56])

In [6]:
np.array([1,2,3,4,4,'syeeda', 4+9j]) #converted to a string in the output 



array(['1', '2', '3', '4', '4', 'syeeda', '(4+9j)'], dtype='<U64')

In [7]:
np.array([1,2,3,4,5.5]) #converting all data into float

array([1. , 2. , 3. , 4. , 5.5])

In [9]:
np.array([[1,3], [3,4], [6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [10]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [13]:
np.array([1,2,3], ndmin=30)  #no_of_brackets = 30

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [15]:
np.array([1,2,3], dtype = complex) #converting a number into complex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [25]:
arr = np.array([(1,2), (4,5)], dtype = [('a', '<i2'), ('b','<i8')])
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [26]:
type(arr[0][0]) #1--> a (i2)

numpy.int16

In [28]:
type(arr[0][1])#2--> b (i8)

numpy.int64

In [31]:
arr = np.array([(1,3),(3,4)])

In [32]:
arr

array([[1, 3],
       [3, 4]])

In [38]:
mat = np.matrix(arr)

In [35]:
l = [3,4,5,67]

In [36]:
np.asarray(l)

array([ 3,  4,  5, 67])

In [37]:
np.asanyarray(l)

array([ 3,  4,  5, 67])

In [39]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [40]:
issubclass(np.matrix, np.ndarray)

True

In [41]:
issubclass(np.ndarray, np.matrix)

False

In [44]:
a = arr

In [45]:
b = np.copy(arr)

In [46]:
arr[0][0] = 67

In [47]:
arr

array([[67,  3],
       [ 3,  4]])

In [48]:
a

array([[67,  3],
       [ 3,  4]])

In [49]:
b

array([[1, 3],
       [3, 4]])

In [50]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [51]:
arr[-1]

array([3, 4])

In [52]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [54]:
a =np.fromfunction(lambda i,j: i==j, (4,4)) #generate an array according to the function given


In [55]:
type(a)

numpy.ndarray

In [56]:
a

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [57]:
b = np.fromfunction(lambda i,j : i*j, (3,3))

In [58]:
b

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [60]:
gen = (i*i for i in range(5))

In [61]:
def test(x):
    yield x

In [62]:
test(5)

<generator object test at 0x7f94103a82e0>

In [63]:
gen

<generator object <genexpr> at 0x7f94103a8190>

In [64]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [66]:
np.fromiter(range(5), dtype=float)

array([0., 1., 2., 3., 4.])

In [68]:
np.fromstring('1,2,3,3', sep=',', dtype = int)

array([1, 2, 3, 3])

In [70]:
np.fromstring("645 7383 8337 736", sep = " ", dtype = complex)

array([ 645.+0.j, 7383.+0.j, 8337.+0.j,  736.+0.j])

In [71]:
l = [3,4,4,4,1,3,22,2]

In [72]:
np.array(l)

array([ 3,  4,  4,  4,  1,  3, 22,  2])

In [73]:
arr1 = np.array([[1,2,3,4],[2,3,4,5], [4,5,6,7]])

In [74]:
type(arr1)

numpy.ndarray

In [75]:
arr1.ndim #it gives dimension --> 2-D

2

In [76]:
 arr1.size #total number of elements

12

In [78]:
arr1.shape #n*m

(3, 4)

In [79]:
arr.dtype

dtype('int64')

In [82]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[2,3,3],[4,5,6]]])

In [83]:
arr2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 3],
        [4, 5, 6]]])

In [85]:
arr2.size

12

In [86]:
arr2.ndim

3

In [89]:
arr2.shape

(2, 2, 3)

In [98]:
arr4 = np.array([[[[1,2],[2,1]],
                  [[2,3],[3,2]],
                  [[4,5],[5,6]],
                 [[4,5],[5,6]]]])
arr4

array([[[[1, 2],
         [2, 1]],

        [[2, 3],
         [3, 2]],

        [[4, 5],
         [5, 6]],

        [[4, 5],
         [5, 6]]]])

In [99]:
arr4.ndim

4

In [101]:
arr4.shape #2*2 --> n*m, 4--> 4-D

(1, 4, 2, 2)

In [102]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [103]:
np.arange(6.5)

array([0., 1., 2., 3., 4., 5., 6.])

In [106]:
np.arange(10.5,9,-0.3)

array([10.5, 10.2,  9.9,  9.6,  9.3])

In [107]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [109]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [110]:
np.linspace(0.3, 0.5,10)

array([0.3       , 0.32222222, 0.34444444, 0.36666667, 0.38888889,
       0.41111111, 0.43333333, 0.45555556, 0.47777778, 0.5       ])

In [112]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [114]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [116]:
np.zeros((2,4,5,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [117]:
np.ones(4)

array([1., 1., 1., 1.])

In [119]:
np.ones((4,4,5,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
        

In [120]:
np.ones((2,3,1))+10

array([[[11.],
        [11.],
        [11.]],

       [[11.],
        [11.],
        [11.]]])

In [121]:
np.empty(7)

array([0., 1., 2., 3., 4., 5., 6.])

In [122]:
np.empty((3,5))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304]])

In [123]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [127]:
np.linspace(2,4,4,endpoint = False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [130]:
np.linspace([1,6],3, endpoint = False, axis=0)

array([[1.  , 6.  ],
       [1.04, 5.94],
       [1.08, 5.88],
       [1.12, 5.82],
       [1.16, 5.76],
       [1.2 , 5.7 ],
       [1.24, 5.64],
       [1.28, 5.58],
       [1.32, 5.52],
       [1.36, 5.46],
       [1.4 , 5.4 ],
       [1.44, 5.34],
       [1.48, 5.28],
       [1.52, 5.22],
       [1.56, 5.16],
       [1.6 , 5.1 ],
       [1.64, 5.04],
       [1.68, 4.98],
       [1.72, 4.92],
       [1.76, 4.86],
       [1.8 , 4.8 ],
       [1.84, 4.74],
       [1.88, 4.68],
       [1.92, 4.62],
       [1.96, 4.56],
       [2.  , 4.5 ],
       [2.04, 4.44],
       [2.08, 4.38],
       [2.12, 4.32],
       [2.16, 4.26],
       [2.2 , 4.2 ],
       [2.24, 4.14],
       [2.28, 4.08],
       [2.32, 4.02],
       [2.36, 3.96],
       [2.4 , 3.9 ],
       [2.44, 3.84],
       [2.48, 3.78],
       [2.52, 3.72],
       [2.56, 3.66],
       [2.6 , 3.6 ],
       [2.64, 3.54],
       [2.68, 3.48],
       [2.72, 3.42],
       [2.76, 3.36],
       [2.8 , 3.3 ],
       [2.84, 3.24],
       [2.88,

In [131]:
np.linspace([1,6],4, endpoint = False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [133]:
np.logspace(2,3,5) #log(inbetween 2 & 3) , given 5 numbers

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [134]:
np.logspace([2,3],4, axis = 1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [137]:
np.logspace([2],[3], axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [139]:
np.logspace([2],[3], axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [141]:
d = np.linspace(4,7,40)

In [142]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [143]:
d.ndim

1

In [144]:
d.shape

(40,)

In [145]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [146]:
d.reshape(2,1,20) #multiplication answer should be 40--> 2*20

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [147]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [148]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [149]:
np.random.rand(3)

array([0.61164293, 0.84770769, 0.73834371])

In [150]:
np.random.randn(9)

array([ 0.11133789, -2.27214836,  1.07671828,  0.22145761,  0.05394022,
       -0.37201002, -0.68182016, -0.3063488 , -0.10842943])

In [151]:
np.random.randn(2,3)

array([[ 0.54566403,  0.74975449, -0.58197389],
       [-1.05022619,  1.04140584,  0.94248465]])

In [153]:
np.random.randint(5,60,(4,4))

array([[24, 26, 50, 34],
       [24, 38, 55, 24],
       [31,  6, 57, 41],
       [18, 21, 39, 38]])

In [155]:
np.random.randn(2,2,3)

array([[[-0.5343251 , -0.1681828 ,  0.66683005],
        [ 0.05869286, -0.61265753, -0.11686282]],

       [[-0.05587437,  0.4026086 , -0.28367002],
        [-0.24574313, -0.01123477,  0.32330078]]])

In [156]:
arr = np.random.randint(3,9,(3,3))

In [157]:
arr

array([[6, 5, 5],
       [4, 4, 4],
       [5, 7, 4]])

In [160]:
arr.reshape(1,9)

array([[6, 5, 5, 4, 4, 4, 5, 7, 4]])

In [161]:
arr.reshape(9,1)

array([[6],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [7],
       [4]])

In [163]:
arr.reshape(1,1,9)

array([[[6, 5, 5, 4, 4, 4, 5, 7, 4]]])

In [165]:
arr.reshape(3,3,1)

array([[[6],
        [5],
        [5]],

       [[4],
        [4],
        [4]],

       [[5],
        [7],
        [4]]])

In [168]:
arr.reshape(3,-1)

array([[6, 5, 5],
       [4, 4, 4],
       [5, 7, 4]])

In [169]:
arr.reshape(3,-9988) 
#any -ve number given would not affect at all as the new_axis number it assumes by itself as a multiple of 9

array([[6, 5, 5],
       [4, 4, 4],
       [5, 7, 4]])

In [170]:
arr.max()

7

In [171]:
arr.min()

4

In [176]:
arr = np.random.randint(4,100,(5,5))

In [177]:
arr

array([[35, 56, 54, 88, 17],
       [54, 96, 85, 80, 65],
       [23, 46, 63, 64, 18],
       [83, 56, 97, 77, 83],
       [51, 80, 59, 67, 47]])

In [180]:
arr[3:,3:] # 3&4 rows #&4 columns

array([[77, 83],
       [67, 47]])

In [181]:
arr[:,[1,3]] #all rows and 1&2 columns only

array([[56, 88],
       [96, 80],
       [46, 64],
       [56, 77],
       [80, 67]])

In [182]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [183]:
arr[arr>10]

array([35, 56, 54, 88, 17, 54, 96, 85, 80, 65, 23, 46, 63, 64, 18, 83, 56,
       97, 77, 83, 51, 80, 59, 67, 47])

In [186]:
arr*arr

array([[1225, 3136, 2916, 7744,  289],
       [2916, 9216, 7225, 6400, 4225],
       [ 529, 2116, 3969, 4096,  324],
       [6889, 3136, 9409, 5929, 6889],
       [2601, 6400, 3481, 4489, 2209]])

In [208]:
arr1 = np.random.randint(2,4,(3,3))
arr1

array([[2, 3, 2],
       [2, 2, 3],
       [2, 3, 2]])

In [209]:
arr2 = np.random.randint(2,4,(3,3))

In [210]:
arr1*arr2 #element wise operation

array([[6, 6, 6],
       [6, 4, 6],
       [6, 6, 4]])

In [211]:
arr1@arr2 #matrix multiplication

array([[21, 14, 16],
       [21, 14, 16],
       [21, 14, 16]])

In [230]:
arr3 = np.random.randint(2,9,(3,1))

In [231]:
arr1@arr3

array([[29],
       [29],
       [29]])

In [213]:
arr/0

/var/folders/l9/bq8y_50n0hx5qtwqd93nnx4w0000gn/T/ipykernel_14734/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [214]:
arr**2

array([[1225, 3136, 2916, 7744,  289],
       [2916, 9216, 7225, 6400, 4225],
       [ 529, 2116, 3969, 4096,  324],
       [6889, 3136, 9409, 5929, 6889],
       [2601, 6400, 3481, 4489, 2209]])

In [217]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [219]:
a = np.array([1,2,3,4])

In [232]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [233]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [234]:
b = np.array([1,2,3])

In [242]:
b

array([1, 2, 3])

In [235]:
b.ndim

1

In [237]:
c = b.reshape(3,1)

In [239]:
c

array([[1],
       [2],
       [3]])

In [243]:
b

array([1, 2, 3])

In [244]:
c +arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [245]:
b.T #not able to rotate

array([1, 2, 3])

In [248]:
b = np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [247]:
b.T #broadcasting one single data through all the rows

array([[5],
       [6],
       [7]])

In [250]:
arr = np.random.rand(5,4)
arr

array([[0.63796308, 0.49124545, 0.9476031 , 0.1330373 ],
       [0.38680586, 0.77978193, 0.85490608, 0.52374946],
       [0.68486071, 0.80611814, 0.20316507, 0.19983781],
       [0.47251587, 0.09940666, 0.76948255, 0.9192092 ],
       [0.93308665, 0.65351727, 0.62912041, 0.89200699]])

In [251]:
np.sqrt(arr)

array([[0.79872591, 0.70088904, 0.97344908, 0.36474278],
       [0.62193718, 0.88305262, 0.92461131, 0.72370537],
       [0.82756311, 0.89784082, 0.45073836, 0.44703222],
       [0.6873979 , 0.31528822, 0.87720154, 0.95875399],
       [0.9659641 , 0.80840415, 0.79317111, 0.94446122]])

In [252]:
np.exp(arr)

array([[1.89262183, 1.63435045, 2.5795194 , 1.1422926 ],
       [1.47227064, 2.1809966 , 2.35115354, 1.68834619],
       [1.98349553, 2.23919884, 1.22527471, 1.22120467],
       [1.60402464, 1.10451537, 2.15864896, 2.50730684],
       [2.54234441, 1.92229016, 1.87595977, 2.44002184]])

In [253]:
np.log10(arr)

array([[-0.19520445, -0.30870146, -0.02337353, -0.87602658],
       [-0.41250695, -0.10802683, -0.0680816 , -0.28087641],
       [-0.16439775, -0.0936013 , -0.69215095, -0.69932235],
       [-0.3255836 , -1.00258451, -0.11380123, -0.03658564],
       [-0.03007802, -0.18474293, -0.20126623, -0.04963174]])

In [256]:
arr1 = np.random.randint(2,5,(5,5))
arr1

array([[2, 2, 4, 4, 3],
       [4, 2, 3, 3, 2],
       [2, 3, 3, 4, 3],
       [4, 2, 3, 4, 4],
       [4, 3, 3, 4, 3]])

In [257]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.60205999, 0.60205999, 0.47712125],
       [0.60205999, 0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125, 0.60205999, 0.47712125],
       [0.60205999, 0.30103   , 0.47712125, 0.60205999, 0.60205999],
       [0.60205999, 0.47712125, 0.47712125, 0.60205999, 0.47712125]])

In [258]:
np.log(arr1)

array([[0.69314718, 0.69314718, 1.38629436, 1.38629436, 1.09861229],
       [1.38629436, 0.69314718, 1.09861229, 1.09861229, 0.69314718],
       [0.69314718, 1.09861229, 1.09861229, 1.38629436, 1.09861229],
       [1.38629436, 0.69314718, 1.09861229, 1.38629436, 1.38629436],
       [1.38629436, 1.09861229, 1.09861229, 1.38629436, 1.09861229]])

In [259]:
np.random.seed(13)

In [261]:
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])